$(document).ready(
  function(){
  $(".content").hover(
    function(){
      $(this).css("background-color","black");
    }, 
    function(){
      $(this).css("background-color","purple");
    }
    );
  }
  );
